export default {
  base: {
    backgroundSize: 'cover',
    flex: '0 0 auto',
    minHeight: '100vh',
    width: '100%',
    margin: 0,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    background: 'linear-gradient(to bottom, rgba(8, 39, 74,1),rgba(34,34,34,1))',
    backgroundSize: 'auto',
  },
  logo: {
    width: 200,
    height: 200,
  },
  init_input: {
    outline: 'none',
    border: '1px solid #eee',
    padding: 10,
    boxSizing: 'border-box',
    fontSize: '1em',
  },
  firechain: {
    flex: '0 0 auto',
    color: '#FFF',
    textTransform: 'uppercase',
    fontWeight: 700,
    fontSize: '4.5em',
    lineHeight: 1,
    margin: 'auto auto 0px',
    background: 'linear-gradient(to bottom, rgb(4,55,113),#444)',
    fontFamily: 'Titillium Web',
    height: 120,
    width: 120,
    letterSpacing: 0,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 120,
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
  },
  four: {
    flex: '0 0 auto',
    color: '#aaa',
    fontSize: '1em',
    fontWeight: 700,
    margin: '20px auto 40px',
    textAlign: 'center',
    textTransform: 'capitalize',
    padding: '0 10px',
    boxSizing: 'border-box',
  },
  tagline: {
    flex: '0 0 auto',
    color: '#fff',
    fontSize: '1.25em',
    fontWeight: 400,
    margin: '0 auto 20px',
    textAlign: 'center',
    padding: '0 10px',
    boxSizing: 'border-box',
  },
  action_button: {
    flex: '0 0 auto',
    margin: '10px auto auto',
    color: '#222',
    background: '#ccc',
    padding: '15px 30px',
    boxSizing: 'border-box',
    borderRadius: 4,
    textTransform: 'capitalize',
    fontWeight: 700,
    fontSize: '0.9em',
    display: 'flex',
    flexFlow: 'row nowrap',
    alignItems: 'center',
    cursor: 'pointer',
  }
};
